### ISSUE TITLE
code public

### ISSUE THREAD

**Issue by jessapinkman** [martius-lab/caiac#1]
hi, @nuria95 @luator  nice work! When do you plan to release the code?

**Comment by nuria95** [comment]
hi @jessapinkman, thanks for the interest in our work. I am planning to release the code in the next few days!

**Comment by jessapinkman** [comment]
@nuria95 Hello, I am actually working on autonomous driving planning, and I want to apply the CAIAC algorithm to data enhancement, but I have the following questions:
1. In CAIAC, an important assumption is that the interactions between entities are sparse, or even non-existent. But in the planning task, there are interactions between agents other than the ego vehicle (NPC vehicles and pedestrians, between vehicles). Do you think this assumption is still valid in the planning task?
2. In the paper, "we are able to perform counterfactual reasoning by swapping action unaffected parts of the state-space between independent trajectories in the dataset." Can you describe more details of the two scenes (samples) where the states are swapped? Do they need to meet certain conditions (for example, the agents perform very similar actions on the same scene and have the same entities)?

Much appreciate it if you could help me figure it out!

**Comment by nuria95** [comment]
hi @jessapinkman 
I replied you via mail to give you a more extended answer.
If you have more general questions that can help others, please let me know!
